### PR TITLE
fix cpu polling interval

### PR DESCRIPTION
**Pull request by caw742**
To fix my change

### CODE REVIEW

**Comment by cal-pratt** [comment]
Please give me a chance to review the changes before you merge them to master.

What is this change for? Is it really a good idea to work the pi this hard with a 1ms sleep. Will the thrusters even respond to changes this quickly? And does our main loop actually complete within 1ms, or will this cause backpressure in the timer observable?

**Comment by caw742** [comment]
This is undoing #244 which was an arbitrary change to demonstrate incorporating upstream changes in master

**Comment by cal-pratt** [comment]
> This is undoing #244 

Nope! I think you changed the wrong variable haha

in #244 

```
 final class Rov {		                        final class Rov {
      static final long MAX_HEARTBEAT_GAP = 5;      static final long MAX_HEARTBEAT_GAP = 5;  
 -    static final long CPU_POLL_INTERVAL = 1;  +   static final long CPU_POLL_INTERVAL = 10;  
      static final long SLEEP_DURATION = 100;       static final long SLEEP_DURATION = 100;
```

and here you change: 

```
 final class Rov {		                         final class Rov {
      static final long MAX_HEARTBEAT_GAP = 5;       static final long MAX_HEARTBEAT_GAP = 5;
      static final long CPU_POLL_INTERVAL = 10;      static final long CPU_POLL_INTERVAL = 10;
 -    static final long SLEEP_DURATION = 100;   +    static final long SLEEP_DURATION = 1;
```

**Comment by caw742** [comment]
🙃

**Pull request merged**
